version: '3.4'

services:
  db:
     image: mongo
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: mongopassword
     volumes:
       - dbdata:/data/db
     restart: always
     ports:
       - "27017:27017"
  start_db:
    image: mongo
    depends_on:
       - db
    volumes:
       - ./docker-files:/home/.docker
    entrypoint: /home/.docker/wait-for-db.sh db root mongopassword
  workflowserver:
    depends_on:
       - db
    build:
      context: ../..
      dockerfile: ./WorkflowServer/Dockerfile
    ports:
       - "8077:8077"
       - "8078:8078"
    volumes:
       - ./logs:/app/logs
       - ./license:/app/license
    environment:
      ConnectionString: mongodb://root:mongopassword@db:27017/ws?authSource=admin
      Provider: mongodb
      LicensePath: /app/license/  
      DefaultLoggerConfig__FileTarget__0: Debug
      DefaultLoggerConfig__FileTarget__1: Information
      DefaultLoggerConfig__FileTarget__2: Error
      DefaultLoggerConfig__FileSettings__FileName: /app/logs/log.txt
      DefaultLoggerConfig__FileSettings__RollingInterval: Day
      DefaultLoggerConfig__FileSettings__RetainedFileCountLimit: 30
volumes:
    dbdata:
