version: '3.4'

services:
  db:
     image: mcr.microsoft.com/mssql/server:2017-latest
     environment:
       SA_PASSWORD: MyStRoNgPWD12345678
       ACCEPT_EULA: Y
     volumes:
       - dbdata:/var/opt/mssql
     restart: always
     ports:
       - "1433:1433"
  start_db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
       - db
    volumes:
       - ./docker-files:/home/.docker
    entrypoint: /home/.docker/wait-for-db.sh db sa MyStRoNgPWD12345678 wfs
  workflowserver:
    depends_on:
       - db
    build:
      context: ../..
      dockerfile: ./WorkflowServer/Dockerfile
    ports:
       - "8077:8077"
       - "8078:8078"
    volumes:
       - ./logs:/app/logs
       - ./license:/app/license
    environment:
      ConnectionString: Data Source=db;Initial Catalog=wfs;Integrated Security=False;User ID=sa;Password=MyStRoNgPWD12345678
      Provider: mssql
      LicensePath: /app/license/
      DefaultLoggerConfig__FileTarget__0: Debug
      DefaultLoggerConfig__FileTarget__1: Information
      DefaultLoggerConfig__FileTarget__2: Error
      DefaultLoggerConfig__FileSettings__FileName: /app/logs/log.txt
      DefaultLoggerConfig__FileSettings__RollingInterval: Day
      DefaultLoggerConfig__FileSettings__RetainedFileCountLimit: 30
volumes:
    dbdata: